import AnimationMine from "./components/Animation";

export const metadata = {
  title: "Darya's Portfolio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <AnimationMine />
    </>
  );
}
